//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0
pub use super::player::Entity as Player;
pub use super::r#match::Entity as Match;
pub use super::setting::Entity as Setting;
pub use super::tournament::Entity as Tournament;
pub use super::tournament_player::Entity as TournamentPlayer;
